name: Update Bindings
on:
  schedule:
    - cron: '0 15 * * 1-4' # Run every Monday through Thursday at 10:00 am Cayman time (15:00 UTC)
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'staging'
      - 'main'
  
permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    # - name: Use Node.js 19.x
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 19
    #     cache: 'yarn'

    - name: Install OpenAPI Generator
      run: yarn global add @openapitools/openapi-generator-cli

    - name: Generate API bindings
      run: |
        rm -r test/
        openapi-generator-cli generate

    - name: Commit and push changes
      run: |
        git config --local user.email "modabot@ai.moda"
        git config --local user.name "modabot"

        # Check if there are any changes
        git add -A
        git status | grep -q "Changes to be committed"
        if [ $? -eq 0 ]; then
          # Create a new branch with a timestamp
          branch_name="update-bindings-$(TZ='UTC' date --iso-8601=seconds | sed s/:/-/g)"
          git checkout -b "$branch_name"

          git commit -m "Update Go API bindings"
          git push --set-upstream origin "$branch_name"
        fi
